In [1]:
import numpy as np

In [2]:
#Câu hỏi 1: Câu nào sau đây là đúng để tạo mảng 1 chiều từ 0 đến 9
arr = np.arange(0 , 10 , 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Câu hỏi 2: Cách tạo một mảng boolean 3x3 với tất cả giá trị là True
arr = np.ones((3,3)) > 0
arr_1 = np.ones((3,3), dtype=bool)
arr_2 = np.full((3,3), fill_value=True, dtype=bool)
arr, arr_1, arr_2

(array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]),
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]),
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]))

In [6]:
#Câu hỏi 3: Kết quả của đoạn code sau đây:
arr = np.arange(0,10)
print(arr[arr%2==1])


[1 3 5 7 9]


In [7]:
#Câu hỏi 4: Kết quả của đoạn code sau đây:
arr = np.arange(0,10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [9]:
#Câu hỏi 5: Kết quả của đoạn code sau đây:
arr = np.arange(0,10)
arr_2d = arr.reshape(2,-1)
print(arr_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
#Câu hỏi 6: Kết quả của đoạn code sau đây:
arr1 = np.arange(10).reshape (2 , -1)
arr2 = np.repeat(1 ,10).reshape(2 , -1)
c = np.concatenate([arr1 ,arr2] ,axis =0)
print("Result: \n" ,c )

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
#Câu hỏi 7: Kết quả của đoạn code sau đây:
arr1 = np.arange(10).reshape (2 , -1)
arr2 = np.repeat(1 ,10).reshape(2 , -1)
c = np.concatenate([arr1 ,arr2] ,axis =1)
print("Result: \n" ,c )

Result: 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [12]:
#Câu hỏi 8: Kết quả của đoạn code sau đây:
arr = np.array([1,2,3])
print(np.repeat(arr,3))
print(np.tile(arr,3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [18]:
#Câu hỏi 9: Kết quả của đoạn code sau đây:
a = np.array([2, 6, 1, 9,10, 3, 27])
index = np.nonzero((a>=5) & (a<=10))
print('result', a[index])

result [ 6  9 10]


In [19]:
#Câu hỏi 10: Kết quả của đoạn code sau đây:
def maxx (x , y ) :
    if x >= y :
        return x
    else :
        return y

a = np.array([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array([6 ,3 ,4 ,8 ,9 ,7 ,1])

pair_max = np.vectorize(maxx ,otypes =[float])
print(pair_max(a , b))

[6. 7. 9. 8. 9. 7. 5.]


In [20]:
#Câu hỏi 11: Kết quả của đoạn code sau đây:
a = np.array([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array([6 ,3 ,4 ,8 ,9 ,7 ,1])

print('Result: ', np.where(a<b, b, a))

Result:  [6 7 9 8 9 7 5]
